### ISSUE TITLE
PLEASE REMOVE 24HR TIMER FROM PLS DAILY!!! MAKE IT ONCE PER DAY, ANY TIME OF THE DAY!

### ISSUE THREAD

**Issue by FrostFyreAye** [DankMemer/dank-memer-suggestions-and-bugs#1073]
When I use dank memer, I’m always frustrated at the fact that I have to wait 24hrs to use pls daily. This usually results in me losing my daily streak, and not gaining extra coins. Plus, it is a lot harder to complete some missions because of this. Not just me, but many others, too, would like this to change. It would be greatly appreciated! Thanks for reading :)

**Comment by Rearcoplays** [comment]
@FrostFyreAye Many people would simply LOVE this idea. The problem is, people would start cheating. Certain places have different time zones, and for example, if my time is 05:00 and your time is 22:00. I could use a VPN and make my time your time, and then I only have to wait another 7 hours before I can claim my pls daily again. Then, if I switch to someone else's time,  then I can keep on claiming my pls daily over and over again, maybe even 5 times a day. I think this is why Dank Memer Devs will NOT do this, even though it is requested by many people, even me. There will be a lot of cheaters, and unless the Dank Memer Devs can stop this. it will not happen. I hope you understand :)

**Comment by samdabloxyccola** [comment]
this will be 100% abused.
If this: Pls daily: at midnight
and you claimed it on 2359
that's literal abuse, man, as u can do it 2 times in a row

**Comment by PhantomFrenzy151** [comment]
Actually, you can claim daily streak between 24-48 hours, meaning some days you can skip a day without losing the streak.

**Comment by andrewisaboomer** [comment]
> this will be 100% abused.
> If this: Pls daily: at midnight
> and you claimed it on 2359
> that's literal abuse, man, as u can do it 2 times in a row

yes but you still only claim it twice during 2 days

**Comment by andrewisaboomer** [comment]
> @FrostFyreAye Many people would simply LOVE this idea. The problem is, people would start cheating. Certain places have different time zones, and for example, if my time is 05:00 and your time is 22:00. I could use a VPN and make my time your time, and then I only have to wait another 7 hours before I can claim my pls daily again. Then, if I switch to someone else's time, then I can keep on claiming my pls daily over and over again, maybe even 5 times a day. I think this is why Dank Memer Devs will NOT do this, even though it is requested by many people, even me. There will be a lot of cheaters, and unless the Dank Memer Devs can stop this. it will not happen. I hope you understand :)

also dude you dont have to do it per time zone, just midnight for the people at dank memer
i wouldnt really care if it reset at 5pm as long as it resets
