### ISSUE TITLE
Pls kill actually kills

### ISSUE THREAD

**Issue by MultiverShaun** [DankMemer/dank-memer-suggestions-and-bugs#1087]
Pls kill doesn’t really kill the person. But, what if pls kill had a 5% chance to actually kill someone?

The person who killed should then get the money in the victim’s wallet.

**Comment by andrewisaboomer** [comment]
no thats retarded

**Comment by Wise2006** [comment]
Bad idea.

**Comment by PhantomFrenzy151** [comment]
not gonna work out very well

**Comment by Astriccs** [comment]
Hey,

That's a pretty bad idea, as it as a 5% chance of killing somebody, which might not seem a lot but if you look at it from a larger point of view, then it seems a bad Idea. Dank is in 2,789,478 servers, which can include more than 10 thousand members, and many people use it, so if this command was made a reality many people would die each day, and could possibly lose all their items and coins. Even you can. 

*Which will eventually create a lot hassle and people could divert away from dank since if you lose everything you had just cause you that 5% applied to you. If that happens more and more people will start diverting as they die and lose their stuff. Eventually, it can create a complicated mess for dank itself.* 

That italicised section is hypothetical but it presenting the consequences that it __can__ have. 

Hope you understand!

Kind regards.
