### ISSUE TITLE
Please add sound commands back in

### ISSUE THREAD

**Issue by dairypr0duct** [DankMemer/dank-memer-suggestions-and-bugs#1117]
Dank Memer markets itself as a multipurpose bot and it used to be one but without sound commands (arguably the most popular discord bot feature) I believe it fails to meet that. It seems every time I use the bot there are less commands. Many of the NSFW features and even some of the meme features have been removed. Basically the bots only use now is to get images and to create memes. These are great features but I would not necessarily call it a multipurpose bot. I see you guys own a sound bot now but why not combine the two?

**Comment by melmsie** [comment]
"Basically the bots only use now is to get images and to create memes."

uh, have you met our currency system? Nsfw? animals? some utility? It's the very definition of multi-purpose. 

"I see you guys own a sound bot now but why not combine the two?"

Well because they're two different programming languages lol

**Comment by dairypr0duct** [comment]
Currency system is such a waste of time it should be considered a meme. The
other things you mentioned are to get images. Your attitude is terrible for
someone trying to sell something. It's pretty whiny. Gl with your ever-
worsening app dickhead.
