### ISSUE TITLE
Make Dank Memer switch to DND when Gateway or similar issues arise

### ISSUE THREAD

**Issue by NurMarvin** [DankMemer/dank-memer-suggestions-and-bugs#118]
**Is your feature request related to a problem? Please describe.**
Usually when Dank Memer is having issues with the gateway or other things related to Discord, most people are left in the dark as to why their commands don't get any responses.

**Describe the solution you'd like**
Dank Memer could switch to DND when any of such issues arises and optionally change it's status to something like "Gateway Issues" or whatever else fits for the current issue. 
Especially issues like gateway issues _should_ be auto-detectable, even though I'm unsure how possible it is in your code base.

**Describe alternatives you've considered**
N/A

**Additional context**
Example: 
![DiscordCanary_rpPvGAF43K](https://user-images.githubusercontent.com/17235016/79026584-9b08c280-7b89-11ea-9d1e-03338af73e11.png)

**Comment by aetheryx** [comment]
the thing about "gateway issues" is that >90% of the time our shards straight up can't connect. there has never really been a situation where we're connected to the gateway but we can't receive messages. and to display a dnd status, we need to be connected to the gateway.  

so showing a dnd status requires that there are no gateway issues on that specific shard. if memer is having gateway issues in someone's server, that shard will be offline and there isn't anything we can do about it. the only thing this would add is that someone in a guild with a dead shard could go to a different server that does have a working shard and see the "Gateway Issues" dnd status from there. announcement channels are a far better solution to this, which is something we already use  

it could still be added because it's a minimal effort and it wouldn't be confusing, but it's definitely not a priority, will be kept in mind for the rewrite
