### ISSUE TITLE
Auto Lottery is broke?

### ISSUE THREAD

**Issue by adankmemey4264** [DankMemer/dank-memer-suggestions-and-bugs#176]
Hi, I am sending it here because the server is locked for today...I asked this on support earlier but then I made note of myself to take a screenshot just in case the "AL Minimum Amount" in my end is bk

ome or sth. I never withdrew anything at all (you can check from your end), and the Auto Lottery seems to be getting money even though I have already set it that it won't take money for a ticket of the amount is lower than indicated... (this is executed on an inactive server whose owner merely keeps it for emotes btw)
![Screenshot_2020-04-30_140141](https://user-images.githubusercontent.com/63214783/80677939-78b0f780-8aec-11ea-930f-4ed0813d3721.jpg)

![Screenshot_2020-04-30_140157](https://user-images.githubusercontent.com/63214783/80677959-84042300-8aec-11ea-9102-158c0c3ac157.jpg)

Will turn off AL for now until the code for it is checked upon...thanks....

**Comment by RandomTurtleBoi** [comment]
I think it's because you were at 550,038 coins in your bank before and it just detected that you had more than 550k, so it just entered the lottery. Since the lottery is 100 coins, it probably just took 100 and now you have 549k. Next time it probably won't enter the lottery. In settings, it says 'if you have less than the amount shown here, you won't be charged for the autolottery'. You had more, so Dank Memer just entered you. (sorry if i kept repeating myself)
