### ISSUE TITLE
Unclogging the rich list from inactive users

### ISSUE THREAD

**Issue by BewkoofBaba** [DankMemer/dank-memer-suggestions-and-bugs#178]
**Is your feature request related to a problem? Please describe.**
Rich list is filled filthily with users who have been inactive for long time. It would be so much better to have users being active then just be inactive and still show in the list. When user is just active in some other activity on the server and does not play dank, still the user starts showing in rich list for eternity.

**Describe the solution you'd like**
Make passive users as non-passive after certain days of inactivity - like 30 or 50 days. So that such users can be robbed and the rich list can be cleansed plus economy can flow instead of users just hogging coins and never playing it and still stay in rich list.

**Describe alternatives you've considered**
At least allow wallet rob for such long time inactive users if not bankrob.

**Additional context**
Same approach was defined for users hogging inventory.. so why not this.

**Comment by melmsie** [comment]
not a bad idea actually

**Comment by melmsie** [comment]
didn't mean to close

**Comment by kablekompany** [comment]
Looked in some bigger servers that I use to run in to rob grind and its a definite challenge to find a target wallet due to the users who are passive on the board. The buff in pages available (from 5-10) was a great addition to combat this but with passive available, a lot of folks sit in the mode, claim a daily, and rejoined these servers for their emotes, or seemingly something other than memer. So it's turned the grounds that used to be rob wild to robbers being unable to identify a target that would be equitable return for loot. 

There is definite validity in implementing some sort of balance to readily expose non passive wallets or an expiry on passive ones. 

Kudos on submitting a suggestion that isn't solely looking out for the individual user, OP. Rich boards are to this point, a leaderboard. I think it's important in aspects of a player leaderboard that the players on it are indeed playing and not nursing a protected mode. The perpetuity of economy "cash flow" from the previous rob metrics before passive implementation encouraged execution of robs regardless of being able to rob the top player on boards or not, so long as you got the best possible return available. It's definitely difficult to find that return.
