### ISSUE TITLE
Stonks feature 

### ISSUE THREAD

**Issue by glasepto** [DankMemer/dank-memer-suggestions-and-bugs#18]
**Is your feature request related to a problem?** No it’s not 

**Describe the solution you'd like**
I made up an idea of adding stonks to the bot. It’ll basically act like laptops but sort of different. Eg. “Are you sure you want to invest in dankmemer.co? Answer y or n”
After you answer it’ll ask you how much you want to “invest”. After you enter the amount it’ll automatically tell you if it went up or down. It’s like gambling 

**Describe alternatives you've considered**
I haven’t thought of any alternatives to this.

**Additional context**
Maybe leveling up gives you more better companies to invest in which gives you a better multiplier  ( 1+ = dankmemer.co, 10+ = dankmemer.co and Pepe.inc, etc..)

**Comment by melmsie** [comment]
Thank god, someone who wants stonks but not an entire stock market system. This is very feasible, and I'll keep it in mind for sure.

**Comment by DekuHavingASeizure** [comment]
lmao I didn't realize you had the same idea sorry :(

**Comment by The-blackout** [comment]
Pls add this

**Comment by Arj2021** [comment]
A few examples to say instead of just saying if it went up or down would make it more interesting
UP-
   -> this stock (if its a bio one) has found cure for corona virus or something and has went up 250%...
Down - 
   -> this stock has found to be involved in heavy illegal insider trading and wrong earning reports for the last few years and has hence been removed from the market(your investment becomes 0 basically)

**Comment by PhantomFrenzy151** [comment]
In order to make it less like gambling, and more like a stock market, I suggest the stock prices are the same for everyone. This feature already technically exists in another form, (IOTD). All that is needed is to make another IOTD where the only thing buyable are stocks with bigger maximum discounts, and for the item to be sold at full price.
