### ISSUE TITLE
Multiplier

### ISSUE THREAD

**Issue by lyl-jerry** [DankMemer/dank-memer-suggestions-and-bugs#232]
I hope that the multiplier can also increase the winnings in blackjack.

**Comment by Wise2006** [comment]
Blackjack always gives the same amount that you bet (fixed). So, multipliers can't increase the winnings. 
Also, the gamble command was removed due to multipliers making it op. Refer to [this announcement](https://discord.com/channels/470337009886429194/502215543915413504/707654812774301838) for more info.

Thank you!
