### ISSUE TITLE
Passive mode Bad Update

### ISSUE THREAD

**Issue by PoorBii** [DankMemer/dank-memer-suggestions-and-bugs#362]
Dank Memer Had a update recently and I can't give or give on passive mode

Get rid of this new update on passive mode as it's not very matching. Passive mode is where you can't hurt anyone or get hurt and now you can't do nice things.

Put passive mode back to normal and also add a mark next to the leaderboard to show that someone is passive.

**Comment by ToPhu31** [comment]
Bruh, there are blue dashes (links) the marks a user on the "pls rich" board to show that they are not passive, and since, and I quote: "Robbing and Bankrobbing are two of the most unique functions in Dank Memer's currency," then they can't take away 50% of what makes their bot _their bot_ by having most people in passive mode.
