### ISSUE TITLE
Person evading bankrob by leaving server 

### ISSUE THREAD

**Issue by soul0101** [DankMemer/dank-memer-suggestions-and-bugs#431]
When someone tries to rob someone who is online, the person just leaves to evade the heist. There was no outcome. This should be removed and a heist should stop only when the phone is used.

**Comment by DANKSHITMEMER** [comment]
![immagine](https://user-images.githubusercontent.com/65983329/82955993-28746a80-9fb0-11ea-875a-b1aed4d1956c.png)

**Comment by Browtf504** [comment]
i disagree people leave the server because people spam the chat doing pls ttt @person when the chat is spammed the person cant do anything to call the heist off they are basicailly being forced to get robbed the only solution at that point is leaving the server also pls ttt doesnt let them use a phone because it would say thats not a vaild answer robbing servers do this alot to ppl that have alot of money in bank in all channels u can only use dank memer in if someone got a server and robbed u while ttting what would u do?

**Comment by oliverysfx** [comment]
I would suggest the punishment to such chickens is an instant success 100% heist if they leave, the ttt spam has been dealt with already by raising the cooldown

**Comment by andrewisaboomer** [comment]
smh the person gains money if they stop the heist with the phone, so why should leaving the server punish them?
they are already losing out on possible money gain by not using the phone
just make it so that people cant be ttted when they are being heisted so they can use the phone properly

**Comment by andrewisaboomer** [comment]
also whats even wrong with leaving the server it literally does the same thing as calling the police, except they dont get money
would you rather they call the police and you give them the money instead

**Comment by andrewisaboomer** [comment]
tttspam still hasnt been dealt with, even with cooldown with lots of people there is nothing you can do
a 20 person heist will completely screw you over

**Comment by oliverysfx** [comment]
then just spam end smh

**Comment by oliverysfx** [comment]
> smh the person gains money if they stop the heist with the phone, so why should leaving the server punish them?
> they are already losing out on possible money gain by not using the phone
> just make it so that people cant be ttted when they are being heisted so they can use the phone properly

well let's say it's similar to leaving server after robbing

**Comment by andrewisaboomer** [comment]
no it isnt, because the person had the ability to call police, they just decided to leave instead of calling
what if the person decided to leave the server because he was done with the heists and was to lazy to call
theres no point punishing them for leaving because they could have called anyway

**Comment by oliverysfx** [comment]
> no it isnt, because the person had the ability to call police, they just decided to leave instead of calling
> what if the person decided to leave the server because he was done with the heists and was to lazy to call
> theres no point punishing them for leaving because they could have called anyway

think about it this way, from the heisters' point of view, it's fucking annoying when the heist come out to no result because target left

**Comment by soul0101** [comment]
Why do people want this game to be as per their needs. If you don't want to be robbed stay passive, don't stay in robbable servers, be discreet. It's your responsibility to protect your money.
You can't go on crying that people spam pls ttt, that's what makes the game fun. What do you expect us to do? Pls beg Pls fish all day?
It's a strategy.
The game would be too monotonous if one of the commands is too OP. 
Plus if a person is able to heist you after that amount of coordination with his teammates they truly deserve that money.

**Comment by andrewisaboomer** [comment]
then wouldnt it be fucking annoying for when they use the phone and stop the heist? all im saying is that leaving the server is literally the same as using the phone except they dont gain money, so why should they be punished
honestly its also just as frustrating to get screwed over by a phone, explain why it would be more frustrating if they leave instead

also
ok
wait
so
spamming ttt
makes
the
game
fun
smh the phone isnt that op, you have to be online to stop the heist, so its easy to heist anyways
why nerf it by making ttt screw you over?
besides, it doesnt even take that much coordination since donators have 0 second cool down, all you need to do is just spam pls ttt you could do this with only 3 people as long as your in a premium server

all im saying is that leaving the server is literally the same as using a phone, because theres no way to automatically leave a server using a bot or something
all of you guys whining about people leaving the server are just salty that your ttt spam doesnt work
