### ISSUE TITLE
People spamming fake events in official server (and other big dank memer servers)

### ISSUE THREAD

**Issue by inooby333** [DankMemer/dank-memer-suggestions-and-bugs#547]
On the main server, many people post fake events with malicious intent. Whether it be fake coin bombs or events. Since coin bombs and events happen so often, there are many people who fall for this. The events are a copy-paste of real events but with the thing you have to say be "pls slots all" or "pls give (user) all". Please create a rule against this with a fitting punishment. A good way to stop fake event spam is to punish with mute. Examples of these fake events will be attached.
![Screenshot_20200601-190313](https://user-images.githubusercontent.com/65725919/83463191-496b0e80-a43b-11ea-881f-6cb357ddd40c.jpg)
![Screenshot_20200601-190257](https://user-images.githubusercontent.com/65725919/83463193-4b34d200-a43b-11ea-94d5-5afb0481916d.jpg)

**Comment by asianmemeboi** [comment]
Hm yes I've seen this quite often on the Official Dank Memer server too.

**Comment by totallydankmemer** [comment]
lost about 100k from these fake events before lol, from now on i just dont go for any events on the server

**Comment by HongKonger1234** [comment]
I can usually tell it's a fake because of the profile pic, but if the profile is the same as Dank's then it throws me off a little. Just watch out for anything that looks like a command, Dank will never tell you to type any command as part of the events, such as pls bet all or pls give ___ all. If it's not a command, the worst that can happen is you look stupid.

Imo doesn't warrant a mute, unless the guy is trying to get you to type a command.

**Comment by melmsie** [comment]
> lost about 100k from these fake events before lol, from now on i just dont go for any events on the server

It's not that hard to take 1s to see if it's the bot or not, that's 100% on you lmfao

**Comment by melmsie** [comment]
We already mute for these on the official server
