### ISSUE TITLE
Ultimate reversal card

### ISSUE THREAD

**Issue by DankMemerFan** [DankMemer/dank-memer-suggestions-and-bugs#589]
**Describe the solution you'd like**
A much more expensive version of the reversal card that instead of reversing steals, reverses death, giving you back your money and potential lost items

**Describe alternatives you've considered**
Maybe just make it reverse coins. 
Alternatively, make it give back some of the coins.

**Comment by OmegaWarrior04** [comment]
although a super reversal card could not only give you back what someone stole from you, but take that same thing from them (or at least until they have no more).
Example: A steals 1000 from B, B uses card, B gets 2000.
C steals 3000 from D, D uses card but, since D only has 5000, C only gets 5000. (or something happends to D, like dying).

**Comment by HongKonger1234** [comment]
Another idea for ultimate reversal: no infinite revs. If you use an ultimate rev within that time period, thief cannot get your money back.
