### ISSUE TITLE
Prestige

### ISSUE THREAD

**Issue by Ravage777** [DankMemer/dank-memer-suggestions-and-bugs#72]
Hello, I recently realized while trying to prestige that the level was bumped up to level 125 and I didn't realize this and I was curious if it could be brought down. I know more items were added to prestige but I just feel like level 125 is too high. I have also seen other people in the Dank Memer discord asking about it. Thank you for your time, Have a nice day.

**Comment by Hariz420** [comment]
i'm agree with this, It's too high and also the price was increases by 250,000 per level. I hope you can do something about it

**Comment by GrandPlo** [comment]
So, I have been using the bot for about 18 months now and have been actively trying to reach prestige for at least the last 4 of these. Today I reached level 25, only to my horror to find the rules have been changed.

I wrote to support and was explained the rationale. It shouldn’t be too easy and people were achieving it too quickly. Personally I really don’t consider 18 months quickly and I would consider myself fairly active (4-5 times per day).

But what I haven’t done up until now is spammed the bot. I’ve used it as I thought it was intended to be used, as periodic fun.

I am aware that you guys hate spammers and I get it. It causes unnecessary stress on your servers. But, and this is the point of it all, you are now actively encouraging spammers by setting the bar so high that normal use will never allow you to achieve it.

I really think this should be reconsidered and focus should instead be put on those achieving high levels quickly through spamming, rather than making it impossible for normal users to achieve.

**Comment by Iwitrag** [comment]
Actually it's 150 not 125

**Comment by The-blackout** [comment]
It’s 125..

**Comment by Iwitrag** [comment]
> It’s 125..

No it is 150.

![image](https://user-images.githubusercontent.com/6575704/78252262-ddc7fc00-74f2-11ea-9e31-85726f4ab4f9.png)

**Comment by The-blackout** [comment]
125

**Comment by melmsie** [comment]
Was reduced to 100
