### ISSUE TITLE
“Pls hunt” when fighting a dragon

### ISSUE THREAD

**Issue by NoNameLolOk** [DankMemer/dank-memer-suggestions-and-bugs#737]
In the “pls hunt” when fighting a dragon the time is too short for typing the long sentences. Plz make the time longer like 15 seconds or more for long sentences. Also, my connection isn’t always good so it sends like 4-5 seconds. Plz change it.

**Comment by andrewisaboomer** [comment]
yeah i feel like the boss events can be super easy for some people and super hard
like what if dank memer lagged by 5 seconds and you said pls fish or smth during that time
or what if ur really bad at typing
like for me i feel like the dragon events are way too easy because i can type fairly fast but its unfair for some people
