### ISSUE TITLE
Great enhancement feature 

### ISSUE THREAD

**Issue by thatonegamer-69-69** [DankMemer/dank-memer-suggestions-and-bugs#864]
Problem: I sometimes get annoyed when I have to wait 5 minutes for automeme and autonsfw to work.

Solution: adding lower intervals for the bot to use in automeme and autonsfw.

Alternatives I tried: making another bot say pls meme and pls (nsfw category) every few minutes, but dank memer does not respond to bots.

**Comment by Chubonyo** [comment]
Using another bot it against Dank memer TOS

**Comment by andrewisaboomer** [comment]
not sure if this is allowed, but couldn't you just write a macro to do those?
i mean, it doesn't affect the currency in any way

**Comment by thatonegamer-69-69** [comment]
What is a macro

**Comment by andrewisaboomer** [comment]
like an autohotkey program, its usually something that makes it so that when you do a specific combination of keys the program will do stuff for you
if you make the program type pls meme and send on loop, youd be able to basically have an auto pls meme command, except you would need to be on discord
