### ISSUE TITLE
pls search (IDEA)

### ISSUE THREAD

**Issue by promages** [DankMemer/dank-memer-suggestions-and-bugs#917]
make searching the sewer have less chance of getting an apple as its 100% according to my experience.
make searching the tree have a chance to get apples along with coins and be able to fall out & die.
make searching the dumpster be able to get apples aswell but with a smaller chance
and why the fuck is there a goddamn hobo in my attic lmao

**Comment by andrewisaboomer** [comment]
i agree with the first 3 (sorta), but i kinda dont agree with the 4th
like its a super small chance to die to begin with, and the attic gives a lot of coins, so i feel that its balanced
for the first one, i dont think its 100% (theres chances to die and get coins and such), but i get apples at least 50% of the time and i feel that it should be reduced
number 2 makes sense because tree gives tons of coins and so it should kill
number 3 just makes sense

**Comment by melmsie** [comment]
changes to search coming soon
