### ISSUE TITLE
I think passive mode is too OP

### ISSUE THREAD

**Issue by CatscratchV** [DankMemer/dank-memer-suggestions-and-bugs#942]
I think passive mode is too OP because then no one can rob. I think you should either remove or nerf passive mode. One solution could be that they earn money and exp like 3x slower . Another solution would be to add something to be able to rob someone in passive mode once. If you just make it like 10k or something per day for passive mode that would also be a solution. Or you could just completely remove it. 
I hope you take my suggestion and please nerf passive mode and because that makes banks pretty much useless.

**Comment by PhantomFrenzy151** [comment]
passive mode is fine as is. some people just want to take a break

**Comment by andrewisaboomer** [comment]
passive mode was created so that people can chill in servers without being robbed like crazy in dank memer
nerfing passive would be stupid
robbing would be immensely unfair if you could rob someone but they couldnt rob you
besides, passive people cant share/gift, get items/coins, lose some winnings from slots/gambling, cant spam switching on and off, and on top of that can't rob people or heist them
all of this so they cant be robbed/heisted
dont you think thats good enough

**Comment by andrewisaboomer** [comment]
honestly if this was added passive mode would basically just be dank memer on ultra hard master mode there literally wouldnt be any benefits at all

**Comment by CatscratchV** [comment]
I just think at least if you turn it off you get a small multiplier or something? because then it actually is worth it to turn it off.

**Comment by oliverysfx** [comment]
I mean there has already been enough nerfs

**Comment by oliverysfx** [comment]
the main thing about passive is because bankrob was added

**Comment by oliverysfx** [comment]
which made robbing too op

**Comment by oliverysfx** [comment]
so the passive mode was to nerf it

**Comment by oliverysfx** [comment]
also, you don't gain multi by being outside of passive, but you do lose 30% of winning if you are in passive
